# 引用包

In [1]:
import functools
import os
import json
import re
import torch
from tqdm import tqdm
from torch_geometric.data import *
import threading
import networkx as nx

filePath="./raw_data/"
filelist = os.listdir(filePath)
import hashlib
def stringtomd5(originstr):
    originstr = originstr.encode("utf-8")
    signaturemd5 = hashlib.sha256()
    signaturemd5.update(originstr)
    return signaturemd5.hexdigest()

# 时间戳转换函数

from datetime import datetime, timezone
import time
import pytz
from time import mktime
from datetime import datetime
import time
def ns_time_to_datetime(ns):
    """
    :param ns: int 纳秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00.000000000
    """
    dt = datetime.fromtimestamp(int(ns) // 1000000000)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    s += '.' + str(int(int(ns) % 1000000000)).zfill(9)
    return s


def ns_time_to_datetime_US(ns):
    """
    :param ns: int 纳秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00.000000000
    """
    tz = pytz.timezone('US/Eastern')
    dt = pytz.datetime.datetime.fromtimestamp(int(ns) // 1000000000, tz)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    s += '.' + str(int(int(ns) % 1000000000)).zfill(9)
    return s

def time_to_datetime_US(s):
    """
    :param ns: int 秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00
    """
    tz = pytz.timezone('US/Eastern')
    dt = pytz.datetime.datetime.fromtimestamp(int(s), tz)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    
    return s

def datetime_to_ns_time(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    timeStamp = int(time.mktime(timeArray))
    timeStamp = timeStamp * 1000000000
    return timeStamp

def datetime_to_ns_time_US(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    tz = pytz.timezone('US/Eastern')
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    dt = datetime.fromtimestamp(mktime(timeArray))
    timestamp = tz.localize(dt)
    timestamp=timestamp.timestamp()
    timeStamp = timestamp * 1000000000
    return int(timeStamp)

def datetime_to_timestamp_US(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    tz = pytz.timezone('US/Eastern')
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    dt = datetime.fromtimestamp(mktime(timeArray))
    timestamp = tz.localize(dt)
    timestamp=timestamp.timestamp()
    timeStamp = timestamp
    return int(timeStamp)


FileNotFoundError: [Errno 2] No such file or directory: './raw_data/'

In [2]:
# 时间戳转换函数

from datetime import datetime, timezone
import time
import pytz
from time import mktime
from datetime import datetime
import time
def ns_time_to_datetime(ns):
    """
    :param ns: int 纳秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00.000000000
    """
    dt = datetime.fromtimestamp(int(ns) // 1000000000)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    s += '.' + str(int(int(ns) % 1000000000)).zfill(9)
    return s


def ns_time_to_datetime_US(ns):
    """
    :param ns: int 纳秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00.000000000
    """
    tz = pytz.timezone('US/Eastern')
    dt = pytz.datetime.datetime.fromtimestamp(int(ns) // 1000000000, tz)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    s += '.' + str(int(int(ns) % 1000000000)).zfill(9)
    return s

def time_to_datetime_US(s):
    """
    :param ns: int 秒时间戳
    :return: datetime   格式为 2013-10-10 23:40:00
    """
    tz = pytz.timezone('US/Eastern')
    dt = pytz.datetime.datetime.fromtimestamp(int(s), tz)
    s = dt.strftime('%Y-%m-%d %H:%M:%S')
    
    return s

def datetime_to_ns_time(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    timeStamp = int(time.mktime(timeArray))
    timeStamp = timeStamp * 1000000000
    return timeStamp

def datetime_to_ns_time_US(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    tz = pytz.timezone('US/Eastern')
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    dt = datetime.fromtimestamp(mktime(timeArray))
    timestamp = tz.localize(dt)
    timestamp=timestamp.timestamp()
    timeStamp = timestamp * 1000000000
    return int(timeStamp)

def datetime_to_timestamp_US(date):
    """
    :param date: str 格式为  %Y-%m-%d %H:%M:%S   例如 2013-10-10 23:40:00
    :return: 纳秒时间戳
    """
    tz = pytz.timezone('US/Eastern')
    timeArray = time.strptime(date, "%Y-%m-%d %H:%M:%S")
    dt = datetime.fromtimestamp(mktime(timeArray))
    timestamp = tz.localize(dt)
    timestamp=timestamp.timestamp()
    timeStamp = timestamp
    return int(timeStamp)


In [3]:
filelist

['ta1-cadets-e3-official.json',
 'ta1-cadets-e3-official.json.1',
 'ta1-cadets-e3-official.json.2',
 'ta1-cadets-e3-official-1.json',
 'ta1-cadets-e3-official-1.json.1',
 'ta1-cadets-e3-official-1.json.2',
 'ta1-cadets-e3-official-1.json.3',
 'ta1-cadets-e3-official-1.json.4',
 'ta1-cadets-e3-official-2.json',
 'ta1-cadets-e3-official-2.json.1']

In [4]:
ns_time_to_datetime_US(1523028709886158284)

'2018-04-06 11:31:49.886158284'

In [5]:
len(filelist)

10

In [6]:
len("./raw_data/ta1-cadets-e3-official.json")

38

# 新建数据库表的sql脚本

首先创建一个名为tc_cadet_dataset_db的数据库，然后执行下面的sql 语句创建table

# 连接数据库

In [7]:
# 连接postgessql 数据库，将数据存入数据库中
import psycopg2

from psycopg2 import extras as ex
connect = psycopg2.connect(database = 'tc_cadet_dataset_db',
                           user = 'postgres',
                           password = 'Ssys8.21',
                           port = '5432'#一般是5432
                          )



# 创建一个cursor来执行数据库的操作
cur = connect.cursor()

In [174]:
tt=cur.execute("""
    delete from node2id where 1=1;
""")
print(tt)
connect.commit()  #需要手动提交

None


In [169]:
#发生错误时需要回滚
connect.rollback()

In [17]:
#关闭数据库连接
cur.close()
connect.close()

# 处理套接字节点

In [64]:
# 遍历数据集
netobjset=set()
netobj2hash={}# 
datalist=[]
for file in tqdm(filelist):
        with open(filePath + file, "r") as f:
            for line in f:
#                 pass
                if "NetFlowObject" in line:
                    
                    try:
                        res=re.findall('NetFlowObject":{"uuid":"(.*?)"(.*?)"localAddress":"(.*?)","localPort":(.*?),"remoteAddress":"(.*?)","remotePort":(.*?),',line)[0]

                        nodeid=res[0]
                        srcaddr=res[2]
                        srcport=res[3]
                        dstaddr=res[4]
                        dstport=res[5]

                        nodeproperty=srcaddr+","+srcport+","+dstaddr+","+dstport # 只关注向哪里发起的网络流 合理么？
                        hashstr=stringtomd5(nodeproperty)
                        netobj2hash[nodeid]=[hashstr,nodeproperty]
                        netobj2hash[hashstr]=nodeid
                        netobjset.add(hashstr)
                    except:
                            # 228786个文件节点是没有路径的，那么关于这种事件应该如何处理呢？ 直接扔掉?
                        pass
#                     print(match)



100%|██████████| 10/10 [00:45<00:00,  4.51s/it]


In [79]:
datalist=[]
for i in netobj2hash.keys():
    if len(i)!=64:
        datalist.append([i]+[netobj2hash[i][0]]+netobj2hash[i][1].split(","))

#写入数据库


sql = '''insert into netflow_node_table
                     values %s
        '''
ex.execute_values(cur,sql, datalist,page_size=10000)
connect.commit()  #需要手动提交

# 处理进程节点数据

In [100]:
scusess_count=0
fail_count=0
subject_objset=set()
subject_obj2hash={}# 
for file in tqdm(filelist):
        with open(filePath + file, "r") as f:
            for line in f:
                if "Event" in line:
                    subject_uuid=re.findall('"subject":{"com.bbn.tc.schema.avro.cdm18.UUID":"(.*?)"}(.*?)"exec":"(.*?)"',line)
                    try:
#                         (subject_uuid[0][-1])
                        subject_obj2hash[subject_uuid[0][0]]=subject_uuid[0][-1]
                        scusess_count+=1
                    except:
                        try:
                            subject_obj2hash[subject_uuid[0][0]]="null"
                        except:
                            pass
#                             print(line)
#                         print(line)                        
                        fail_count+=1
                        

100%|██████████| 10/10 [09:51<00:00, 59.13s/it]


In [109]:
datalist=[]
for i in subject_obj2hash.keys():
    if len(i)!=64:
        datalist.append([i]+[stringtomd5(subject_obj2hash[i]),subject_obj2hash[i]])
        
#写入数据库


sql = '''insert into subject_node_table
                     values %s
        '''
ex.execute_values(cur,sql, datalist,page_size=10000)
connect.commit()  #需要手动提交

# 处理文件节点数据

In [114]:
# 先找出属于文件类型的节点
file_node=set()
for file in tqdm(filelist):
        with open(filePath + file, "r") as f:
            for line in f:
                if "com.bbn.tc.schema.avro.cdm18.FileObject" in line:
                    Object_uuid=re.findall('FileObject":{"uuid":"(.*?)",',line) 
                    try:
                        file_node.add(Object_uuid[0])
                    except:
                        print(line)

100%|██████████| 10/10 [00:52<00:00,  5.21s/it]


In [115]:
len(file_node)

2305159

In [123]:
# 遍历数据集  处理节点的数据

#NetFlowObject
#Subject
#FileObject
file_obj2hash={}# 

node_types=set()
for file in tqdm(filelist):
        with open(filePath + file, "r") as f:
            for line in f:
                if '{"datum":{"com.bbn.tc.schema.avro.cdm18.Event"' in line:                  
                    #转成json处理 速度太慢了
#                     jdata=json.loads(line)                       
#                     print(line)
                    predicateObject_uuid=re.findall('"predicateObject":{"com.bbn.tc.schema.avro.cdm18.UUID":"(.*?)"}',line)
                    if len(predicateObject_uuid)>0:# 找到uuid
                        if predicateObject_uuid[0] in file_node:# 客体是文件节点
                            if '"predicateObjectPath":null,' not in line and '<unknown>'not in line:
                                path_name=re.findall('"predicateObjectPath":{"string":"(.*?)"',line) 
                                file_obj2hash[predicateObject_uuid[0]]=path_name
                     
#                     try:
             
#                         node_dic[predicateObject_uuid[0]]={"path":path_name[0]}
                        
#                     except:
#                         print(line)
#                     node_types.add(node_type)

100%|██████████| 10/10 [03:44<00:00, 22.49s/it]


In [130]:
datalist=[]
for i in file_obj2hash.keys():
    if len(i)!=64:
        datalist.append([i]+[stringtomd5(file_obj2hash[i][0]),file_obj2hash[i][0]])

# 写入数据库
sql = '''insert into file_node_table
                     values %s
        '''
ex.execute_values(cur,sql, datalist,page_size=10000)
connect.commit()  #需要手动提交

# 处理事件数据

In [152]:
sql="""
select * from netflow_node_table;
"""
cur.execute(sql)
records = cur.fetchall()

In [157]:
for i in records:
    node_list.append([i[0],"netflow",i[-2]+":"+i[-1]])

In [158]:
records

[('71A3EC7D-3678-11E8-BF66-D9AA8AFF4A69',
  'b73bfba47623fda99313c4d45e49df2dbc7a46e883038182398b9b75a028086c',
  '10.0.6.23',
  '123',
  '10.0.4.1',
  '123'),
 ('25251C47-2F6D-529A-99DD-164B02137950',
  'b73bfba47623fda99313c4d45e49df2dbc7a46e883038182398b9b75a028086c',
  '10.0.6.23',
  '123',
  '10.0.4.1',
  '123'),
 ('A8E89D09-36C2-11E8-BF66-D9AA8AFF4A69',
  '6a4f685d16d644f0cd2291df78f60d7907804d29ee8cc5deab2c41896ba4f892',
  '128.55.12.73',
  '27274',
  '128.55.12.59',
  '9094'),
 ('A909D605-36C2-11E8-BF66-D9AA8AFF4A69',
  '86f299b99b7f39179ac05f36b42b69cfe263ba9399edb15497522dd122e68a4e',
  '128.55.12.73',
  '17781',
  '128.55.12.60',
  '9094'),
 ('A909E9A6-36C2-11E8-BF66-D9AA8AFF4A69',
  'c092633b4585415f2c7298cc63b085a7504f7299b7429ff5a0d54e7f0e32ca32',
  '128.55.12.73',
  '24235',
  '128.55.12.63',
  '9094'),
 ('A90A0689-36C2-11E8-BF66-D9AA8AFF4A69',
  '0337085922ff147de899aaff42162a34dfaa8b49ad0eb63aecb9546dea42591c',
  '128.55.12.73',
  '64522',
  '128.55.12.62',
  '9094'),


In [159]:
node_list[-1]

['61F09963-25B5-5402-AC94-58C24731D479', 'netflow', '128.55.12.10:53']

In [166]:

# 生成node2id表的数据
node_list={}
##################################################################################################
sql="""
select * from file_node_table;
"""
cur.execute(sql)
records = cur.fetchall()

for i in records:    
    node_list[i[1]]=["file",i[-1]]

file_uuid2hash={}
for i in records:
    file_uuid2hash[i[0]]=i[1]
##################################################################################################    
sql="""
select * from subject_node_table;
"""
cur.execute(sql)
records = cur.fetchall()

for i in records:
    node_list[i[1]]=["subject",i[-1]]

subject_uuid2hash={}
for i in records:
    subject_uuid2hash[i[0]]=i[1]
##################################################################################################
sql="""
select * from netflow_node_table;
"""
cur.execute(sql)
records = cur.fetchall()

for i in records:
    
    node_list[i[1]]=["netflow",i[-2]+":"+i[-1]]

net_uuid2hash={}
for i in records:
    net_uuid2hash[i[0]]=i[1]

In [175]:
node_list_database=[]
node_index=0
for i in node_list:
    node_list_database.append([i]+node_list[i]+[node_index])
    node_index+=1

In [176]:
#写入数据库
sql = '''insert into node2id
                     values %s
        '''
ex.execute_values(cur,sql, node_list_database,page_size=10000)
connect.commit()  #需要手动提交

In [179]:
# 构建nodeid 与msg之间的构建  创建字典变量 nodeid2msg
sql="select * from node2id ORDER BY index_id;"
cur.execute(sql)
rows = cur.fetchall()

nodeid2msg={}  # 可以实现 nodeid 转 msg      node hash 转 nodeid
for i in rows:
    nodeid2msg[i[0]]=i[-1]
    nodeid2msg[i[-1]]={i[1]:i[2]}  #0-828297

In [260]:
datalist=[]
reverse=["EVENT_ACCEPT","EVENT_RECVFROM","EVENT_RECVMSG"]        
for file in tqdm(filelist):
        with open(filePath + file, "r") as f:
            for line in f:
                if '{"datum":{"com.bbn.tc.schema.avro.cdm18.Event"' in line and "EVENT_FLOWS_TO" not in line:
                    
                    subject_uuid=re.findall('"subject":{"com.bbn.tc.schema.avro.cdm18.UUID":"(.*?)"}',line)
                    predicateObject_uuid=re.findall('"predicateObject":{"com.bbn.tc.schema.avro.cdm18.UUID":"(.*?)"}',line)
                    if len(subject_uuid) >0 and len(predicateObject_uuid)>0:
                        if subject_uuid[0] in subject_uuid2hash\
                        and (predicateObject_uuid[0] in file_uuid2hash or predicateObject_uuid[0] in net_uuid2hash):
                            #开始处理事件数据
                            relation_type=re.findall('"type":"(.*?)"',line)[0]
                            time_rec=re.findall('"timestampNanos":(.*?),',line)[0]
                            time_rec=int(time_rec) # 将时间转成秒为单位
                            subjectId=subject_uuid2hash[subject_uuid[0]]
                            if predicateObject_uuid[0] in file_uuid2hash:
                                objectId=file_uuid2hash[predicateObject_uuid[0]]
                            else:
                                objectId=net_uuid2hash[predicateObject_uuid[0]]
#                                 print(line)
                            if relation_type in reverse:
                                datalist.append([objectId,nodeid2msg[objectId],relation_type,subjectId,nodeid2msg[subjectId],time_rec])
                            else:
                                datalist.append([subjectId,nodeid2msg[subjectId],relation_type,objectId,nodeid2msg[objectId],time_rec])

               
     
                     

100%|██████████| 10/10 [10:16<00:00, 61.66s/it]


In [265]:
#写入数据库


sql = '''insert into event_table
                     values %s
        '''
ex.execute_values(cur,sql, datalist,page_size=10000)
connect.commit()  #需要手动提交

In [269]:
ns_time_to_datetime_US(1522706863163352079)

'2018-04-02 18:07:43.163352079'

In [205]:
nodeid2msg[subject_uuid2hash["1EC08BAB-36C3-11E8-BF66-D9AA8AFF4A69"]]

198244

In [268]:
nodeid2msg[198240]

{'subject': 'vmstat'}

In [262]:
rel=set()
for i in tqdm(datalist):
#     if i[2]=="EVENT_FLOWS_TO":
#         print("src:",nodeid2msg[i[1]]," dst:",nodeid2msg[i[4]])
    rel.add(i[2])

100%|██████████| 29727441/29727441 [00:10<00:00, 2968657.22it/s]


In [263]:
rel

{'EVENT_ACCEPT',
 'EVENT_CLOSE',
 'EVENT_CONNECT',
 'EVENT_CREATE_OBJECT',
 'EVENT_EXECUTE',
 'EVENT_FCNTL',
 'EVENT_LINK',
 'EVENT_LSEEK',
 'EVENT_MMAP',
 'EVENT_MODIFY_FILE_ATTRIBUTES',
 'EVENT_OPEN',
 'EVENT_READ',
 'EVENT_RECVFROM',
 'EVENT_RECVMSG',
 'EVENT_RENAME',
 'EVENT_SENDMSG',
 'EVENT_SENDTO',
 'EVENT_TRUNCATE',
 'EVENT_UNLINK',
 'EVENT_WRITE'}

In [12]:
rel={'EVENT_ACCEPT',
 'EVENT_CLOSE',
 'EVENT_CONNECT',
 'EVENT_CREATE_OBJECT',
 'EVENT_EXECUTE',
 'EVENT_FCNTL',#文件控制
#  'EVENT_FLOWS_TO', #流向
 'EVENT_LINK', #链接
 'EVENT_LSEEK',#移动文件指针
 'EVENT_MMAP',  #内存映射
 'EVENT_MODIFY_FILE_ATTRIBUTES', #修改文件属性
 'EVENT_OPEN',
 'EVENT_READ',
 'EVENT_RECVFROM',#接收数据
 'EVENT_RECVMSG',#接收数据
 'EVENT_RENAME',#
 'EVENT_SENDMSG',
 'EVENT_SENDTO',
 'EVENT_TRUNCATE',#截断文件
 'EVENT_UNLINK',
 'EVENT_WRITE'}

In [ ]:
{"datum":{"com.bbn.tc.schema.avro.cdm18.Event":{"uuid":"736425EE-6347-5E3C-93AA-F346790630CB","sequence":{"long":11345},"type":"EVENT_CONNECT","threadId":{"int":100231},"hostId":"83C8ED1F-5045-DBCD-B39F-918F0DF4F851","subject":{"com.bbn.tc.schema.avro.cdm18.UUID":"1EC08BAB-36C3-11E8-BF66-D9AA8AFF4A69"},"predicateObject":{"com.bbn.tc.schema.avro.cdm18.UUID":"1EEE5041-36C3-11E8-BF66-D9AA8AFF4A69"},"predicateObjectPath":null,"predicateObject2":null,"predicateObject2Path":null,"timestampNanos":1522707230023346842,"name":{"string":"aue_connect"},"parameters":{"array":[]},"location":null,"size":null,"programPoint":null,"properties":{"map":{"return_value":"0","address":"128.55.12.10","port":"53","host":"83c8ed1f-5045-dbcd-b39f-918f0df4f851","fd":"5","exec":"lsof","ppid":"2549"}}}},"CDMVersion":"18","source":"SOURCE_FREEBSD_DTRACE_CADETS"}

In [141]:
subject_uuid

['EA7EAF6E-36EB-11E8-BF66-D9AA8AFF4A69']

In [142]:
predicateObject_uuid

['7D1ED996-14BC-B054-BC14-9D5394B0F6C8']

# 分层hash处理特征

In [270]:
# 生成数据集之前，首先算出所有node 和edge的特征映射字典，这样数据集生成速度会加快


from sklearn.feature_extraction import FeatureHasher
from torch_geometric.transforms import NormalizeFeatures

from sklearn import preprocessing #导入用于数据标准化的模块
import numpy as np
# 将path 转成分层的list

FH_string=FeatureHasher(n_features=16,input_type="string")
FH_dict=FeatureHasher(n_features=16,input_type="dict")


def path2higlist(p):
    l=[]
    spl=p.strip().split('/')
    for i in spl:
        if len(l)!=0:
            l.append(l[-1]+'/'+i)
        else:
            l.append(i)
#     print(l)
    return l

def ip2higlist(p):
    l=[]
    spl=p.strip().split('.')
    for i in spl:
        if len(l)!=0:
            l.append(l[-1]+'.'+i)
        else:
            l.append(i)
#     print(l)
    return l
def list2str(l):
    s=''
    for i in l:
        s+=i
    return s

In [271]:
list2str(ip2higlist('10.10.14.42:10'))

'1010.1010.10.1410.10.14.42:10'

In [273]:
node_msg_vec=[]
node_msg_dic_list=[]
for i in tqdm(nodeid2msg.keys()):
    if type(i)==int:
        if 'netflow' in nodeid2msg[i].keys():
            higlist=['netflow']
            higlist+=ip2higlist(nodeid2msg[i]['netflow'])
            
        if 'file' in nodeid2msg[i].keys():
            higlist=['file']
            higlist+=path2higlist(nodeid2msg[i]['file'])
            
#             print(higlist)
        if 'subject' in nodeid2msg[i].keys():
            higlist=['subject']
            higlist+=path2higlist(nodeid2msg[i]['subject'])
        node_msg_dic_list.append(list2str(higlist))

100%|██████████| 536484/536484 [00:01<00:00, 387528.45it/s]


In [318]:
node2higvec=[]
for i in tqdm(node_msg_dic_list):
    vec=FH_string.transform([i]).toarray()
    node2higvec.append(vec)


100%|██████████| 268242/268242 [00:41<00:00, 6518.60it/s]


In [319]:
node2higvec=np.array(node2higvec).reshape([-1,16])

In [ ]:
include_edge_type=[
    "EVENT_WRITE",
    "EVENT_READ",
    "EVENT_CLOSE",
    "EVENT_OPEN",
    "EVENT_EXECUTE",
    "EVENT_SENDTO",
    "EVENT_RECVFROM",
#     "EVENT_CONNECT",
#     "EVENT_ACCEPT",
]

In [23]:
rel2id={}
index=1
for i in include_edge_type:
    rel2id[index]=i
    rel2id[i]=index
    index+=1

In [24]:
rel2id

{1: 'EVENT_WRITE',
 'EVENT_WRITE': 1,
 2: 'EVENT_READ',
 'EVENT_READ': 2,
 3: 'EVENT_CLOSE',
 'EVENT_CLOSE': 3,
 4: 'EVENT_OPEN',
 'EVENT_OPEN': 4,
 5: 'EVENT_EXECUTE',
 'EVENT_EXECUTE': 5,
 6: 'EVENT_SENDTO',
 'EVENT_SENDTO': 6,
 7: 'EVENT_RECVFROM',
 'EVENT_RECVFROM': 7}

In [25]:
# 生成edge type one-hot变量
relvec=torch.nn.functional.one_hot(torch.arange(0, len(rel2id.keys())//2), num_classes=len(rel2id.keys())//2)

In [26]:
# 将不同的relation type转为 变量 rel2vec   通过该变量，可以将字符串的关系类型转成ont hot编码
rel2vec={}
for i in rel2id.keys():
    if type(i) is not int:
        rel2vec[i]= relvec[rel2id[i]-1]
        rel2vec[relvec[rel2id[i]-1]]=i

In [27]:
rel2vec

{'EVENT_WRITE': tensor([1, 0, 0, 0, 0, 0, 0]),
 tensor([1, 0, 0, 0, 0, 0, 0]): 'EVENT_WRITE',
 'EVENT_READ': tensor([0, 1, 0, 0, 0, 0, 0]),
 tensor([0, 1, 0, 0, 0, 0, 0]): 'EVENT_READ',
 'EVENT_CLOSE': tensor([0, 0, 1, 0, 0, 0, 0]),
 tensor([0, 0, 1, 0, 0, 0, 0]): 'EVENT_CLOSE',
 'EVENT_OPEN': tensor([0, 0, 0, 1, 0, 0, 0]),
 tensor([0, 0, 0, 1, 0, 0, 0]): 'EVENT_OPEN',
 'EVENT_EXECUTE': tensor([0, 0, 0, 0, 1, 0, 0]),
 tensor([0, 0, 0, 0, 1, 0, 0]): 'EVENT_EXECUTE',
 'EVENT_SENDTO': tensor([0, 0, 0, 0, 0, 1, 0]),
 tensor([0, 0, 0, 0, 0, 1, 0]): 'EVENT_SENDTO',
 'EVENT_RECVFROM': tensor([0, 0, 0, 0, 0, 0, 1]),
 tensor([0, 0, 0, 0, 0, 0, 1]): 'EVENT_RECVFROM'}

In [330]:
## 保存结果变量
torch.save(node2higvec,"node2higvec")
torch.save(rel2vec,"rel2vec")

# 生成数据集

In [8]:
# 加载节点特征字典，边特征字典数据
node2higvec=torch.load("./node2higvec")
rel2vec=torch.load("./rel2vec")

In [28]:
for day in tqdm(range(2,14)):
    start_timestamp=datetime_to_ns_time_US('2018-04-'+str(day)+' 00:00:00')
    end_timestamp=datetime_to_ns_time_US('2018-04-'+str(day+1)+' 00:00:00')
    sql="""
    select * from event_table
    where
          timestamp_rec>'%s' and timestamp_rec<'%s'
           ORDER BY timestamp_rec;
    """%(start_timestamp,end_timestamp)
    cur.execute(sql)
    events = cur.fetchall()
    print('2018-04-'+str(day)," events count:",str(len(events)))
    edge_list=[]
    for e in events:
        edge_temp=[int(e[1]),int(e[4]),e[2],e[5]]
        if e[2] in include_edge_type:
#         if True:
            edge_list.append(edge_temp)
    print('2018-04-'+str(day)," edge list len:",str(len(edge_list)))
    # 保存数据集数据
    dataset = TemporalData()
    src = []
    dst = []
    msg = []
    t = []
    for i in edge_list:
        src.append(int(i[0]))
        dst.append(int(i[1]))
    #     msg.append(torch.cat([torch.from_numpy(node2higvec_bn[i[0]]), rel2vec[i[2]], torch.from_numpy(node2higvec_bn[i[1]])] ))
        msg.append(torch.cat([torch.from_numpy(node2higvec[i[0]]), rel2vec[i[2]], torch.from_numpy(node2higvec[i[1]])] ))
        t.append(int(i[3]))

    dataset.src = torch.tensor(src)
    dataset.dst = torch.tensor(dst)
    dataset.t = torch.tensor(t)
    dataset.msg = torch.vstack(msg)
    dataset.src = dataset.src.to(torch.long)
    dataset.dst = dataset.dst.to(torch.long)
    dataset.msg = dataset.msg.to(torch.float)
    dataset.t = dataset.t.to(torch.long)
    torch.save(dataset, "./train_graph/graph_4_"+str(day)+".TemporalData.simple")  

  0%|          | 0/12 [00:00<?, ?it/s]

2018-04-2  events count: 600488
2018-04-2  edge list len: 445378


  8%|▊         | 1/12 [00:21<03:54, 21.30s/it]

2018-04-3  events count: 2453951
2018-04-3  edge list len: 1758192


 17%|█▋        | 2/12 [01:25<07:45, 46.56s/it]

2018-04-4  events count: 2395521
2018-04-4  edge list len: 1677700


 25%|██▌       | 3/12 [02:30<08:15, 55.04s/it]

2018-04-5  events count: 2746323
2018-04-5  edge list len: 1936142


 33%|███▎      | 4/12 [03:43<08:15, 61.93s/it]

2018-04-6  events count: 2892308
2018-04-6  edge list len: 2022481


 42%|████▏     | 5/12 [04:59<07:50, 67.23s/it]

2018-04-7  events count: 3265428
2018-04-7  edge list len: 2284034


 50%|█████     | 6/12 [06:25<07:20, 73.49s/it]

2018-04-8  events count: 3055020
2018-04-8  edge list len: 2133829


 58%|█████▊    | 7/12 [07:50<06:26, 77.30s/it]

2018-04-9  events count: 2414970
2018-04-9  edge list len: 1627876


 67%|██████▋   | 8/12 [08:54<04:52, 73.17s/it]

2018-04-10  events count: 2598188
2018-04-10  edge list len: 1849650


 75%|███████▌  | 9/12 [10:06<03:38, 72.73s/it]

2018-04-11  events count: 2781685
2018-04-11  edge list len: 1953716


 83%|████████▎ | 10/12 [11:21<02:26, 73.34s/it]

2018-04-12  events count: 2680274
2018-04-12  edge list len: 1897902


 92%|█████████▏| 11/12 [12:35<01:13, 73.70s/it]

2018-04-13  events count: 1843285
2018-04-13  edge list len: 1241968


100%|██████████| 12/12 [13:28<00:00, 67.36s/it]
